/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.command.CommandInvoker;
import org.example.controllers.MenuMenuController;
import org.example.controllers.RestaurantMenuController;
import org.example.controllers.ReviewMenuController;
import org.example.interfaces.IHandler;
import org.example.utils.ConsoleHandler;
import org.example.utils.ReviewerMenu;


public class App {

    public static void main(String[] args) {

        IHandler handler = new ConsoleHandler();

        CommandInvoker invokerRestaurant = new CommandInvoker();
        CommandInvoker invokerMenu = new CommandInvoker();
        CommandInvoker invokerReview = new CommandInvoker();

        RestaurantMenuController restaurantMenuController = new RestaurantMenuController(handler, invokerRestaurant);
        MenuMenuController menuMenuController = new MenuMenuController(handler, invokerMenu);
        ReviewMenuController reviewMenuController = new ReviewMenuController(handler, invokerReview);

        ReviewerMenu menu = new ReviewerMenu(handler, restaurantMenuController, menuMenuController, reviewMenuController);
        menu.displayMenu();

    }
}
