/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.services.MenuService;
import org.example.services.RestaurantService;
import org.example.utils.ConsoleHandler;
import org.example.utils.IHandler;
import org.example.utils.IMenuCommand;
import org.example.utils.MenuManagementMenu;
import org.example.utils.RestaurantMenu;

import java.util.Map;

public class App {
    private static Boolean exit = false;
    private static final IHandler handler = new ConsoleHandler();
    private static final RestaurantService restaurantService = new RestaurantService();
    private static final MenuService menuService = new MenuService();

    private static final Map<Integer, IMenuCommand> menuCommands = Map.of(
      1, new RestaurantMenu(restaurantService, handler),
      2, new MenuManagementMenu(menuService, handler),
      3, ()-> {
          handler.writeLine("Saliendo del sistema");
          exit = true;
      }
    );

    public static void main(String[] args) {

        String message = "\nBievenido a la reseña de restaurantes \n¿Qué deseas hacer?\n1. Gestionar restaurantes\n2. Gestionar menús\n3. Salir";
        while (!exit) {
            handler.writeLine(message);
            int choice = Integer.parseInt(handler.readLine());
            if (choice >= 1 && choice <= 3) {
                menuCommands.get(choice).displayMenu();
            }
            else {
                handler.writeLine("Opción inválida");
            }
        }
    }
}
