/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.reviews;

import org.example.reviews.controllers.restaurant.CreateRestaurantController;
import org.example.reviews.controllers.restaurant.FindRestaurantsController;
import org.example.reviews.controllers.restaurant.RemoveRestaurantController;
import org.example.reviews.controllers.restaurant.RestaurantController;
import org.example.reviews.controllers.restaurant.UpdateRestaurantController;
import org.example.reviews.services.restaurants.CreateRestaurantImpl;
import org.example.reviews.services.restaurants.FindRestaurantsImpl;
import org.example.reviews.services.restaurants.RemoveRestaurantImpl;
import org.example.reviews.services.restaurants.RestaurantService;
import org.example.reviews.services.restaurants.UpdateRestaurantImpl;
import org.example.reviews.utils.AppMenu;
import org.example.reviews.utils.ConsoleUtil;

public class App {

    public static void main(String[] args) {
        ConsoleUtil console  = new ConsoleUtil();
        RestaurantService restaurantService = new RestaurantService(
                new CreateRestaurantImpl(console),
                new FindRestaurantsImpl(),
                new UpdateRestaurantImpl(console),
                new RemoveRestaurantImpl(console));

        AppMenu appMenu = new AppMenu(
                new RestaurantController(
                        new CreateRestaurantController(restaurantService),
                        new FindRestaurantsController(restaurantService),
                        new UpdateRestaurantController(restaurantService),
                        new RemoveRestaurantController(restaurantService),console),console);

        appMenu.execute();
    }
}
