/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.reviews;

import org.example.reviews.controllers.dish.DishController;
import org.example.reviews.controllers.menu.MenuController;
import org.example.reviews.controllers.restaurant.RestaurantController;
import org.example.reviews.controllers.reviews.ReviewController;
import org.example.reviews.observer.NotificationSystem;
import org.example.reviews.services.dishes.DishesService;
import org.example.reviews.services.menus.MenuService;
import org.example.reviews.services.restaurants.RestaurantService;
import org.example.reviews.services.reviews.ReviewService;
import org.example.reviews.utils.AppMenu;
import org.example.reviews.utils.ConsoleUtil;

public class App {

    public static void main(String[] args) {
        ConsoleUtil console  = new ConsoleUtil();

        RestaurantService restaurantService = new RestaurantService(console);
        DishesService dishesService = new DishesService(console);
        MenuService menuService = new MenuService(console);

        NotificationSystem notificationSystem = new NotificationSystem();
        ReviewService reviewService = new ReviewService(console, notificationSystem);


        RestaurantController restaurantController = new RestaurantController(restaurantService,console);
        DishController dishController = new DishController(dishesService, console);
        MenuController menuController = new MenuController(menuService, dishController,console);
        ReviewController reviewController = new ReviewController(reviewService, console);

        AppMenu appMenu = new AppMenu(restaurantController, menuController, reviewController,() -> System.exit(0), console);

        appMenu.execute();
    }
}
