/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.reviews;

import org.example.reviews.controllers.restaurant.CreateRestaurantController;
import org.example.reviews.controllers.restaurant.RestaurantController;
import org.example.reviews.services.restaurants.CreateRestaurant;
import org.example.reviews.services.restaurants.RestaurantService;
import org.example.reviews.utils.AppMenu;
import org.example.reviews.utils.ConsoleUtil;

public class App {

    public static void main(String[] args) {
        ConsoleUtil console  = new ConsoleUtil();
        RestaurantService restaurantService = new RestaurantService(new CreateRestaurant(console));
        AppMenu appMenu = new AppMenu(new RestaurantController(new CreateRestaurantController(restaurantService),console), console);

        appMenu.execute();
    }
}
