/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.controllers.MenuController;
import org.example.controllers.RestauranteController;
import org.example.utils.IManejadorConsola;
import org.example.utils.ManejadorConsola;
import org.example.utils.MenuApp;


public class App {

    public static void main(String[] args) {
        IManejadorConsola manejadorConsola = new ManejadorConsola();
        MenuApp menu = new MenuApp(new MenuController(), new RestauranteController(),manejadorConsola);
        menu.displayMenu();
    }
}
